name: bilim_all
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  persistent_bottom_nav_bar: ^5.0.2
  bloc_concurrency: ^0.2.1
  youtube_player_flutter: ^8.1.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  json_annotation: ^4.8.0
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  shared_preferences: ^2.0.20
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  intl_utils: ^2.8.2
flutter:
  generate: true
  assets:
    - assets/images/bitmap/
    - assets/images/svg/
  uses-material-design: true


